name:                Chess
version:             0.2.0.0
github:              "stu214634/Chess"
license:             BSD3
author:              "Stu214634"
maintainer:          "stu214634@mail.uni-kiel.de"
copyright:           "2022 Stu214634"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
#
#- aeson
#- servant-server
#- servant
#- servant-client
#- wai
#- warp
#- HTTP
#- http-client
#- http-client-tls
#- hip
description:         Please see the README on GitHub at <https://github.com/stu214634/Chess#readme>

dependencies:
- base >= 4.7 && < 5
- parallel
- template-haskell
- hashtables
- hashable
- vector

library:
  source-dirs: src

executables:
  Chess:
    main: Main.hs
    source-dirs: [app, src]
    ghc-options:
    - -rtsopts
    - -O2
    - -Wall
    dependencies:
    - base
    


tests:
  Chess-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - Chess
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
